### ISSUE TITLE
Jpeg color distortion in macOS (F3, Ctrl+Q)

### ISSUE THREAD

**Issue by VicDobrov** [double-commander/doublecmd#30] opened 2022-11-03 11:36 UTC
Jpeg is shown incorrectly in builds of Double Commander 1.0 and higher for Mac OS 10.14.....12.6. There is not a single WLX plugin.
The correct JPG display is only available in version 0.9.10b.
How to fix this problem?

Double Commander 1.1.0 alpha Revision: 10401
Commit: d016db930 Build date: 2022/10/15
Lazarus: 2.3.0.0 FPC: 3.2.2
Platform: x86_64-Darwin-cocoa
OS version: Mac OS X 10.16.0

**Comment by alexx2000** [comment] 2022-11-03 15:54
#21
I cannot reproduce under macOS 10.14.

**Comment by VicDobrov** [comment] 2022-11-03 22:32
The bug of viewing the ZUP is on all versions of Mac OS - I checked on many. The message lists all versions from Mojave to Monterey: 10.14.....12.6

**Comment by Neustradamus** [comment] 2023-08-20 00:05
@VicDobrov: The official and good organization/repository:
- https://github.com/doublecmd/
- https://github.com/doublecmd/doublecmd

Please open at the good place.

Linked to:
- https://github.com/double-commander/doublecmd/issues/7

**Comment by alexx2000** [comment] 2023-12-23 20:35
Should be fixed in the latest snapshots.
https://github.com/doublecmd/doublecmd/issues/1290

**Closed by alexx2000** 2023-12-23 20:35 UTC
