### ISSUE TITLE
Give owner rights to the official dev

### ISSUE THREAD

**Issue by Neustradamus** [double-commander/doublecmd#8] opened 2021-03-12 22:57 UTC
Hello @TheNicker, @vitaliyg2, and all,

Can you give all rights to @alexx2000, the official dev of the project?

The official place is:
- https://github.com/doublecmd/doublecmd

Thanks in advance.

Regards,

Neustradamus

**Comment by TheNicker** [comment] 2021-03-13 08:45
Discussion continues at #7

**Comment by vitaliyg2** [comment] 2021-03-13 08:58
Hi @Neustradamus,

For what purpose right are needed?

**Comment by Neustradamus** [comment] 2021-03-13 16:00
To add @alexx2000, the official dev, to keep the hand on the double-commander organization username ^^

Now, we know that the official place is https://github.com/doublecmd.

@TheNicker and @vitaliyg2, please look the diff between the official repo and your fork and create a PR directly with your personal account and archive and remove this repo when all fork will be removed.

**Comment by vitaliyg2** [comment] 2021-03-13 16:12
@Neustradamus thanks for the clarification.

@TheNicker based on Neustradamus reply I guess it is safe to close this issue as a duplicate of #7

**Comment by TheNicker** [comment] 2021-03-13 17:36
> Now, we know that the official place is https://github.com/doublecmd.

I've explained in #7.  if it's not clear we may dig deeper.

Closing this issue as duplicate of #7.

**Closed** 2021-03-13 17:36 UTC
Labels: duplicate

**Comment by Neustradamus** [comment] 2021-03-13 17:39
It is not same, this ticket is to add owner rights of this organization to @alexx2000.

**Comment by Neustradamus** [comment] 2021-03-13 17:49
@TheNicker: It is here: https://github.com/orgs/double-commander/people "Invite member".

**Comment by TheNicker** [comment] 2021-03-13 17:52
I've converted your profile from outside collaborator to a member.
Please join the Double commander telegram group so we could talk freely at https://t.me/DoubleCommander

**Comment by Neustradamus** [comment] 2021-03-13 18:22
@TheNicker: Thanks for "member" rights.
Please add @alexx2000 with owner rights, by default it is "member" like me...
Near the username, on the gear, "change role"...

**Comment by Neustradamus** [comment] 2021-03-13 18:22
I do not use Telegram...

**Comment by TheNicker** [comment] 2021-03-13 18:53
I'm trying to figure out what are you trying to benefit from having @alexx0000 as a co-owner ?
Since this repository is independent from the official one.

**Comment by vitaliyg2** [comment] 2021-03-14 03:40
The telegram group appears to be read only

**Comment by TheNicker** [comment] 2021-03-14 05:39
Fixed

**Comment by Neustradamus** [comment] 2023-08-17 01:40
Dear all,

I wait you about the different steps which must be done to solve all.

Thanks in advance.
